import Head from "next/head";

import fetchPortFolioData from "../pages/api/portfolio";

import Main from "../public/components/main/main";
import Footer from "../public/components/footer/footer";

export default function Home({ portfolio }) {
  return (
    <div>
      <Head>
        <title>Jegadees</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicon-logo.png"
        ></link>
      </Head>
      <div>
        <Main data={portfolio}></Main>
        <Footer data={portfolio.contact}></Footer>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const portfolio = await fetchPortFolioData({ method: "GET" }, {});
  return {
    props: {
      portfolio,
    },
  };
}
